<?php

namespace Proxies\__CG__\make\tareaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Curso extends \make\tareaBundle\Entity\Curso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'materia', 'nomProfesor', 'apeProfesor', 'emailProfesor', 'tareas', 'horasClase', 'horarios');
        }

        return array('__isInitialized__', 'id', 'materia', 'nomProfesor', 'apeProfesor', 'emailProfesor', 'tareas', 'horasClase', 'horarios');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Curso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateria($materia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateria', array($materia));

        return parent::setMateria($materia);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateria', array());

        return parent::getMateria();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomProfesor($nomProfesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomProfesor', array($nomProfesor));

        return parent::setNomProfesor($nomProfesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomProfesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomProfesor', array());

        return parent::getNomProfesor();
    }

    /**
     * {@inheritDoc}
     */
    public function setApeProfesor($apeProfesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApeProfesor', array($apeProfesor));

        return parent::setApeProfesor($apeProfesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getApeProfesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApeProfesor', array());

        return parent::getApeProfesor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailProfesor($emailProfesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailProfesor', array($emailProfesor));

        return parent::setEmailProfesor($emailProfesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailProfesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailProfesor', array());

        return parent::getEmailProfesor();
    }

    /**
     * {@inheritDoc}
     */
    public function addTarea(\make\tareaBundle\Entity\Tarea $tareas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTarea', array($tareas));

        return parent::addTarea($tareas);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTarea(\make\tareaBundle\Entity\Tarea $tareas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTarea', array($tareas));

        return parent::removeTarea($tareas);
    }

    /**
     * {@inheritDoc}
     */
    public function getTareas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTareas', array());

        return parent::getTareas();
    }

    /**
     * {@inheritDoc}
     */
    public function addHorasClase(\make\tareaBundle\Entity\HorasClase $horasClase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHorasClase', array($horasClase));

        return parent::addHorasClase($horasClase);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHorasClase(\make\tareaBundle\Entity\HorasClase $horasClase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHorasClase', array($horasClase));

        return parent::removeHorasClase($horasClase);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasClase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasClase', array());

        return parent::getHorasClase();
    }

    /**
     * {@inheritDoc}
     */
    public function addHorario(\make\tareaBundle\Entity\Horarios $horarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHorario', array($horarios));

        return parent::addHorario($horarios);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHorario(\make\tareaBundle\Entity\Horarios $horarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHorario', array($horarios));

        return parent::removeHorario($horarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarios', array());

        return parent::getHorarios();
    }

}
