parameters:
#    maketarea.example.class: make\tareaBundle\Example

services:
#    maketarea.example:
#        class: %maketarea.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
