parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: smaketarea
    database_user: root
    database_password: '#s3cure'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: bb25b1b2d9d452a5b330bc9f90d04df131bdf7ae
    database_path: null
