security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        make\tareaBundle\Entity\Usuario: plaintext

    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                provider:   users
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/app$, roles: ROLE_USER }
        - { path: ^/app,  roles: ROLE_USER }
        - { path: ^/login_check$, roles: ROLE_USER}

    providers:
        administrators:
            entity: { class: make\tareaBundle\Entity\Usuario }
        users:
            entity: { class: make\tareaBundle\Entity\Usuario }