<?php

namespace make\tareaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HorariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorariosRepository extends EntityRepository
{
}
